<?php

namespace App\Filament\Pages;

use App\Filament\Widgets\AdvancedProjectsChart;
use App\Filament\Widgets\ProjectsChart;
use App\Filament\Widgets\SubscribersOverview;
use App\Filament\Widgets\TotalProjects;
use App\Filament\Widgets\UsersOverview;
use EightyNine\FilamentAdvancedWidget\AdvancedWidgetConfiguration;
use Filament\Pages\Dashboard as BaseDashboard;

class Dashboard extends BaseDashboard
{
    protected static ?string $navigationIcon = 'heroicon-o-home';
    protected static ?string $activeNavigationIcon = 'heroicon-s-home';

    //protected static string $view = 'filament.pages.dashboard';


    public function getHeaderWidgetsColumns(): int
    {
        return 20;
    }


    protected function getHeaderWidgets(): array
    {
        return [
            UsersOverview::class,
            TotalProjects::class,
            SubscribersOverview::class
        ];
    }

    public function getVisibleWidgets(): array
    {
        return [
            AdvancedProjectsChart::class
        ];// TODO: Change the autogenerated stub
    }

}
